In [1]:
import pandas as pd 
df = pd.read_json("data.json")
df

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
0,techie_koramangala,420,9800,Software Engineer,310,Arjun M.,💻 Full-stack @ SaaS startup\n☕ Working from ca...
1,blrcoder_girl,150,6300,Tech Creator,120,Riya Codes,👩‍💻 Python | ML | Roadmaps\n🎥 Coding Reels + D...
2,hsr_startup_stories,980,22400,Media,95,Startup Stories HSR,🚀 Interviews with Bangalore founders\n🎙️ Weekl...
3,cloud_dev_blr,210,4500,Engineer,60,Naveen DevOps,☁️ AWS | Docker | K8s\n📍 Sarjapur\ngithub.com/...
4,koramangala_coffee_lover,300,7900,Cafe Explorer,180,Sana B.,☕ Reviewing Bangalore’s hidden coffee spots\n📍...
...,...,...,...,...,...,...,...
102,bangalore_backend,90,4800,Tech,60,BLR Backend Devs,🔧 Python | Go | Node\n📍 BLR\nbackendblr.tech
103,ecity_techies,140,3900,Community,55,E-city Techies,💼 Tech park life\n📍 Electronic City\necitytech...
104,fullstack_blr_club,110,7200,Community,85,Fullstack BLR Club,💻 MERN | Python | DevOps\n📍 JP Nagar\nfullstac...
105,coding_runners_blr,100,2500,Community,35,Coding Runners,🏃‍♂️ Running + coding\n📍 Cubbon Park\ncodingru...
106,bangalore_engineers_diary,270,8500,Blog,120,Engineers Diary BLR,📘 Life & tech rants\n📍 BLR\nmedium.com/@engine...

In [2]:
df2=df.drop_duplicates().copy()
df2

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
0,techie_koramangala,420,9800,Software Engineer,310,Arjun M.,💻 Full-stack @ SaaS startup\n☕ Working from ca...
1,blrcoder_girl,150,6300,Tech Creator,120,Riya Codes,👩‍💻 Python | ML | Roadmaps\n🎥 Coding Reels + D...
2,hsr_startup_stories,980,22400,Media,95,Startup Stories HSR,🚀 Interviews with Bangalore founders\n🎙️ Weekl...
3,cloud_dev_blr,210,4500,Engineer,60,Naveen DevOps,☁️ AWS | Docker | K8s\n📍 Sarjapur\ngithub.com/...
4,koramangala_coffee_lover,300,7900,Cafe Explorer,180,Sana B.,☕ Reviewing Bangalore’s hidden coffee spots\n📍...
...,...,...,...,...,...,...,...
102,bangalore_backend,90,4800,Tech,60,BLR Backend Devs,🔧 Python | Go | Node\n📍 BLR\nbackendblr.tech
103,ecity_techies,140,3900,Community,55,E-city Techies,💼 Tech park life\n📍 Electronic City\necitytech...
104,fullstack_blr_club,110,7200,Community,85,Fullstack BLR Club,💻 MERN | Python | DevOps\n📍 JP Nagar\nfullstac...
105,coding_runners_blr,100,2500,Community,35,Coding Runners,🏃‍♂️ Running + coding\n📍 Cubbon Park\ncodingru...
106,bangalore_engineers_diary,270,8500,Blog,120,Engineers Diary BLR,📘 Life & tech rants\n📍 BLR\nmedium.com/@engine...

In [3]:
df2.isnull().sum()

username           0
no_of_posts        0
no_of_followers    0
type_of_page       0
no_of_following    0
name               0
bio                0
dtype: int64

In [4]:
df3 = df2.query("no_of_followers>10000")
df3

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
2,hsr_startup_stories,980,22400,Media,95,Startup Stories HSR,🚀 Interviews with Bangalore founders\n🎙️ Weekl...
5,ai_bangalore_news,1340,38000,Media,200,AI Bangalore,🤖 Daily AI news from India\n📢 Startup & resear...
6,techfounder_india,210,19000,Founder,450,Dev Patel,⚡ Building SaaS in Fintech\n📍 Indiranagar\ndev...
8,blrdatascience_daily,540,15100,Media,150,Bangalore DS Daily,📊 Data + AI + ML\n👩‍🏫 Tutorials | Job alerts\n...
11,indiranagar_food_maps,600,12300,Food & Drink,155,Food Maps BLR,🍜 Maps of best places around Indiranagar\n📍 Ba...
12,python_blr_jobs,1200,21000,Community,18,Python Jobs BLR,💼 Python/ML/AI jobs daily\n📍 Bengaluru\npython...
15,techwalk_blr,430,11000,Media,320,Tech Walk Bangalore,🚶 Exploring tech parks & cafes\n📍 Ecoworld | M...
16,itpl_daily,590,14200,Blog,210,ITPL Daily,🏢 Inside Whitefield Tech Life\n🚌 Bus stand sto...
20,machinelearning_blr,490,17800,Community,140,ML Bangalore,🤖 Workshops | Resources\nmlblr.in
27,deeptech_india,900,24000,Media,290,DeepTech India,🛠️ Indian AI + Robotics + Chips\ndeeptechindia.ai
30,koramangala_hustlers,800,18700,Lifestyle,300,Koramangala Hustlers,"💼 Startups, events, coworks\nkorahustlers.com"
32,producthunt_blr,340,10500,Media,190,Product Hunt BLR,🚀 New launches from Indian builders\nproducthu...
37,indiranagar_startuplab,220,12000,Community,160,Startup Lab,🧪 Experiments with early-stage founders\nindir...
40,techpark_memes,350,16000,Comedy,250,Tech Park Memes,"😂 Jokes from Ecospace, Manyata & more\nbit.ly/..."
47,_anujsinghal,1785,681000,Digital creator,248,Anuj Singhal,"Managing Editor, CNBC-Awaaz. Most trusted and ..."
49,bangalore_tech_bro,402,12500,Entrepreneur,890,Rahul | HSR Hustler,🚀 Building the next Unicorn in Fintech\n☕ 3rd ...
51,startuphub_blr,2300,45000,Media,120,Startup Hub Bangalore,🦄 News from the Silicon Valley of India\n📢 Fun...
53,venture_vikram,120,30000,Investor,500,Vikram | Angel Investor,"💸 Helping founders go 0 to 1\nEx-Google, Ex-Am..."
60,ai_bengaluru,150,15200,Tech,140,AI Bengaluru,"🤖 AI trends, events & demos\n📍 BLR\nai-blr.tech"
62,hsr_startup_stories,600,22000,Media,300,HSR Startup Stories,🦄 Founder journeys from HSR\n📍 BLR\nhsrstartup...
67,devlife_bangalore,430,18000,Blog,450,DevLife Bangalore,"💼 Life of BLR developers\n☕ Cafes, layoffs & c..."
70,bangalore_datascience_club,240,12700,Community,110,BLR Data Science Club,📊 ML sessions + Kaggle nights\n📍 MG Road WeWor...
72,react_bangalore,300,14000,Community,200,React Bangalore,⚛️ React meetups & workshops\n📍 BLR\nreactblr.dev
77,startup_grind_bangalore,1100,38000,Community,420,Startup Grind Bangalore,🔥 Founder wisdom + events\n📍 BLR\nstartupgrind...
81,blrcoders_space,340,25000,Community,300,BLR Coders Space,"👨‍💻 Coding news, memes\n📍 BLR\nblrcoders.space"
85,blronlinejobs,560,21000,Media,190,BLR Online Jobs,💼 Hiring in tech daily\n📍 BLR\nblronlinejobs.in
90,indiranagar_startups,320,12500,Media,100,Indiranagar Startups,🦄 Spotlight on early-stage founders\n📍 Indiran...
91,machinelearning_blr,210,19000,Tech,250,Machine Learning BLR,🤖 ML articles & demos\n📍 BLR\nmlblr.tech
100,coders_of_bangalore,300,17000,Community,280,Coders of Bangalore,👨‍💻 Showcasing BLR devs\n📍 BLR\ncodersofbangal...
101,dailydev_bangalore,180,12200,Tech,200,Daily Dev Bangalore,📝 Tips | Tools | Tutorials\n📍 BLR\ndailydevblr.co

In [5]:
df4 =df3.sort_values("username").copy()
df4

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
47,_anujsinghal,1785,681000,Digital creator,248,Anuj Singhal,"Managing Editor, CNBC-Awaaz. Most trusted and ..."
5,ai_bangalore_news,1340,38000,Media,200,AI Bangalore,🤖 Daily AI news from India\n📢 Startup & resear...
60,ai_bengaluru,150,15200,Tech,140,AI Bengaluru,"🤖 AI trends, events & demos\n📍 BLR\nai-blr.tech"
70,bangalore_datascience_club,240,12700,Community,110,BLR Data Science Club,📊 ML sessions + Kaggle nights\n📍 MG Road WeWor...
49,bangalore_tech_bro,402,12500,Entrepreneur,890,Rahul | HSR Hustler,🚀 Building the next Unicorn in Fintech\n☕ 3rd ...
81,blrcoders_space,340,25000,Community,300,BLR Coders Space,"👨‍💻 Coding news, memes\n📍 BLR\nblrcoders.space"
8,blrdatascience_daily,540,15100,Media,150,Bangalore DS Daily,📊 Data + AI + ML\n👩‍🏫 Tutorials | Job alerts\n...
85,blronlinejobs,560,21000,Media,190,BLR Online Jobs,💼 Hiring in tech daily\n📍 BLR\nblronlinejobs.in
100,coders_of_bangalore,300,17000,Community,280,Coders of Bangalore,👨‍💻 Showcasing BLR devs\n📍 BLR\ncodersofbangal...
101,dailydev_bangalore,180,12200,Tech,200,Daily Dev Bangalore,📝 Tips | Tools | Tutorials\n📍 BLR\ndailydevblr.co
27,deeptech_india,900,24000,Media,290,DeepTech India,🛠️ Indian AI + Robotics + Chips\ndeeptechindia.ai
67,devlife_bangalore,430,18000,Blog,450,DevLife Bangalore,"💼 Life of BLR developers\n☕ Cafes, layoffs & c..."
62,hsr_startup_stories,600,22000,Media,300,HSR Startup Stories,🦄 Founder journeys from HSR\n📍 BLR\nhsrstartup...
2,hsr_startup_stories,980,22400,Media,95,Startup Stories HSR,🚀 Interviews with Bangalore founders\n🎙️ Weekl...
11,indiranagar_food_maps,600,12300,Food & Drink,155,Food Maps BLR,🍜 Maps of best places around Indiranagar\n📍 Ba...
37,indiranagar_startuplab,220,12000,Community,160,Startup Lab,🧪 Experiments with early-stage founders\nindir...
90,indiranagar_startups,320,12500,Media,100,Indiranagar Startups,🦄 Spotlight on early-stage founders\n📍 Indiran...
16,itpl_daily,590,14200,Blog,210,ITPL Daily,🏢 Inside Whitefield Tech Life\n🚌 Bus stand sto...
30,koramangala_hustlers,800,18700,Lifestyle,300,Koramangala Hustlers,"💼 Startups, events, coworks\nkorahustlers.com"
20,machinelearning_blr,490,17800,Community,140,ML Bangalore,🤖 Workshops | Resources\nmlblr.in
91,machinelearning_blr,210,19000,Tech,250,Machine Learning BLR,🤖 ML articles & demos\n📍 BLR\nmlblr.tech
32,producthunt_blr,340,10500,Media,190,Product Hunt BLR,🚀 New launches from Indian builders\nproducthu...
12,python_blr_jobs,1200,21000,Community,18,Python Jobs BLR,💼 Python/ML/AI jobs daily\n📍 Bengaluru\npython...
72,react_bangalore,300,14000,Community,200,React Bangalore,⚛️ React meetups & workshops\n📍 BLR\nreactblr.dev
77,startup_grind_bangalore,1100,38000,Community,420,Startup Grind Bangalore,🔥 Founder wisdom + events\n📍 BLR\nstartupgrind...
51,startuphub_blr,2300,45000,Media,120,Startup Hub Bangalore,🦄 News from the Silicon Valley of India\n📢 Fun...
6,techfounder_india,210,19000,Founder,450,Dev Patel,⚡ Building SaaS in Fintech\n📍 Indiranagar\ndev...
40,techpark_memes,350,16000,Comedy,250,Tech Park Memes,"😂 Jokes from Ecospace, Manyata & more\nbit.ly/..."
15,techwalk_blr,430,11000,Media,320,Tech Walk Bangalore,🚶 Exploring tech parks & cafes\n📍 Ecoworld | M...
53,venture_vikram,120,30000,Investor,500,Vikram | Angel Investor,"💸 Helping founders go 0 to 1\nEx-Google, Ex-Am..."

In [6]:
df4.reset_index(drop = True, inplace = True)
df4

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
0,_anujsinghal,1785,681000,Digital creator,248,Anuj Singhal,"Managing Editor, CNBC-Awaaz. Most trusted and ..."
1,ai_bangalore_news,1340,38000,Media,200,AI Bangalore,🤖 Daily AI news from India\n📢 Startup & resear...
2,ai_bengaluru,150,15200,Tech,140,AI Bengaluru,"🤖 AI trends, events & demos\n📍 BLR\nai-blr.tech"
3,bangalore_datascience_club,240,12700,Community,110,BLR Data Science Club,📊 ML sessions + Kaggle nights\n📍 MG Road WeWor...
4,bangalore_tech_bro,402,12500,Entrepreneur,890,Rahul | HSR Hustler,🚀 Building the next Unicorn in Fintech\n☕ 3rd ...
5,blrcoders_space,340,25000,Community,300,BLR Coders Space,"👨‍💻 Coding news, memes\n📍 BLR\nblrcoders.space"
6,blrdatascience_daily,540,15100,Media,150,Bangalore DS Daily,📊 Data + AI + ML\n👩‍🏫 Tutorials | Job alerts\n...
7,blronlinejobs,560,21000,Media,190,BLR Online Jobs,💼 Hiring in tech daily\n📍 BLR\nblronlinejobs.in
8,coders_of_bangalore,300,17000,Community,280,Coders of Bangalore,👨‍💻 Showcasing BLR devs\n📍 BLR\ncodersofbangal...
9,dailydev_bangalore,180,12200,Tech,200,Daily Dev Bangalore,📝 Tips | Tools | Tutorials\n📍 BLR\ndailydevblr.co
10,deeptech_india,900,24000,Media,290,DeepTech India,🛠️ Indian AI + Robotics + Chips\ndeeptechindia.ai
11,devlife_bangalore,430,18000,Blog,450,DevLife Bangalore,"💼 Life of BLR developers\n☕ Cafes, layoffs & c..."
12,hsr_startup_stories,600,22000,Media,300,HSR Startup Stories,🦄 Founder journeys from HSR\n📍 BLR\nhsrstartup...
13,hsr_startup_stories,980,22400,Media,95,Startup Stories HSR,🚀 Interviews with Bangalore founders\n🎙️ Weekl...
14,indiranagar_food_maps,600,12300,Food & Drink,155,Food Maps BLR,🍜 Maps of best places around Indiranagar\n📍 Ba...
15,indiranagar_startuplab,220,12000,Community,160,Startup Lab,🧪 Experiments with early-stage founders\nindir...
16,indiranagar_startups,320,12500,Media,100,Indiranagar Startups,🦄 Spotlight on early-stage founders\n📍 Indiran...
17,itpl_daily,590,14200,Blog,210,ITPL Daily,🏢 Inside Whitefield Tech Life\n🚌 Bus stand sto...
18,koramangala_hustlers,800,18700,Lifestyle,300,Koramangala Hustlers,"💼 Startups, events, coworks\nkorahustlers.com"
19,machinelearning_blr,490,17800,Community,140,ML Bangalore,🤖 Workshops | Resources\nmlblr.in
20,machinelearning_blr,210,19000,Tech,250,Machine Learning BLR,🤖 ML articles & demos\n📍 BLR\nmlblr.tech
21,producthunt_blr,340,10500,Media,190,Product Hunt BLR,🚀 New launches from Indian builders\nproducthu...
22,python_blr_jobs,1200,21000,Community,18,Python Jobs BLR,💼 Python/ML/AI jobs daily\n📍 Bengaluru\npython...
23,react_bangalore,300,14000,Community,200,React Bangalore,⚛️ React meetups & workshops\n📍 BLR\nreactblr.dev
24,startup_grind_bangalore,1100,38000,Community,420,Startup Grind Bangalore,🔥 Founder wisdom + events\n📍 BLR\nstartupgrind...
25,startuphub_blr,2300,45000,Media,120,Startup Hub Bangalore,🦄 News from the Silicon Valley of India\n📢 Fun...
26,techfounder_india,210,19000,Founder,450,Dev Patel,⚡ Building SaaS in Fintech\n📍 Indiranagar\ndev...
27,techpark_memes,350,16000,Comedy,250,Tech Park Memes,"😂 Jokes from Ecospace, Manyata & more\nbit.ly/..."
28,techwalk_blr,430,11000,Media,320,Tech Walk Bangalore,🚶 Exploring tech parks & cafes\n📍 Ecoworld | M...
29,venture_vikram,120,30000,Investor,500,Vikram | Angel Investor,"💸 Helping founders go 0 to 1\nEx-Google, Ex-Am..."

In [7]:
df4["username"] = df4["username"].str.upper()
df4

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
0,_ANUJSINGHAL,1785,681000,Digital creator,248,Anuj Singhal,"Managing Editor, CNBC-Awaaz. Most trusted and ..."
1,AI_BANGALORE_NEWS,1340,38000,Media,200,AI Bangalore,🤖 Daily AI news from India\n📢 Startup & resear...
2,AI_BENGALURU,150,15200,Tech,140,AI Bengaluru,"🤖 AI trends, events & demos\n📍 BLR\nai-blr.tech"
3,BANGALORE_DATASCIENCE_CLUB,240,12700,Community,110,BLR Data Science Club,📊 ML sessions + Kaggle nights\n📍 MG Road WeWor...
4,BANGALORE_TECH_BRO,402,12500,Entrepreneur,890,Rahul | HSR Hustler,🚀 Building the next Unicorn in Fintech\n☕ 3rd ...
5,BLRCODERS_SPACE,340,25000,Community,300,BLR Coders Space,"👨‍💻 Coding news, memes\n📍 BLR\nblrcoders.space"
6,BLRDATASCIENCE_DAILY,540,15100,Media,150,Bangalore DS Daily,📊 Data + AI + ML\n👩‍🏫 Tutorials | Job alerts\n...
7,BLRONLINEJOBS,560,21000,Media,190,BLR Online Jobs,💼 Hiring in tech daily\n📍 BLR\nblronlinejobs.in
8,CODERS_OF_BANGALORE,300,17000,Community,280,Coders of Bangalore,👨‍💻 Showcasing BLR devs\n📍 BLR\ncodersofbangal...
9,DAILYDEV_BANGALORE,180,12200,Tech,200,Daily Dev Bangalore,📝 Tips | Tools | Tutorials\n📍 BLR\ndailydevblr.co
10,DEEPTECH_INDIA,900,24000,Media,290,DeepTech India,🛠️ Indian AI + Robotics + Chips\ndeeptechindia.ai
11,DEVLIFE_BANGALORE,430,18000,Blog,450,DevLife Bangalore,"💼 Life of BLR developers\n☕ Cafes, layoffs & c..."
12,HSR_STARTUP_STORIES,600,22000,Media,300,HSR Startup Stories,🦄 Founder journeys from HSR\n📍 BLR\nhsrstartup...
13,HSR_STARTUP_STORIES,980,22400,Media,95,Startup Stories HSR,🚀 Interviews with Bangalore founders\n🎙️ Weekl...
14,INDIRANAGAR_FOOD_MAPS,600,12300,Food & Drink,155,Food Maps BLR,🍜 Maps of best places around Indiranagar\n📍 Ba...
15,INDIRANAGAR_STARTUPLAB,220,12000,Community,160,Startup Lab,🧪 Experiments with early-stage founders\nindir...
16,INDIRANAGAR_STARTUPS,320,12500,Media,100,Indiranagar Startups,🦄 Spotlight on early-stage founders\n📍 Indiran...
17,ITPL_DAILY,590,14200,Blog,210,ITPL Daily,🏢 Inside Whitefield Tech Life\n🚌 Bus stand sto...
18,KORAMANGALA_HUSTLERS,800,18700,Lifestyle,300,Koramangala Hustlers,"💼 Startups, events, coworks\nkorahustlers.com"
19,MACHINELEARNING_BLR,490,17800,Community,140,ML Bangalore,🤖 Workshops | Resources\nmlblr.in
20,MACHINELEARNING_BLR,210,19000,Tech,250,Machine Learning BLR,🤖 ML articles & demos\n📍 BLR\nmlblr.tech
21,PRODUCTHUNT_BLR,340,10500,Media,190,Product Hunt BLR,🚀 New launches from Indian builders\nproducthu...
22,PYTHON_BLR_JOBS,1200,21000,Community,18,Python Jobs BLR,💼 Python/ML/AI jobs daily\n📍 Bengaluru\npython...
23,REACT_BANGALORE,300,14000,Community,200,React Bangalore,⚛️ React meetups & workshops\n📍 BLR\nreactblr.dev
24,STARTUP_GRIND_BANGALORE,1100,38000,Community,420,Startup Grind Bangalore,🔥 Founder wisdom + events\n📍 BLR\nstartupgrind...
25,STARTUPHUB_BLR,2300,45000,Media,120,Startup Hub Bangalore,🦄 News from the Silicon Valley of India\n📢 Fun...
26,TECHFOUNDER_INDIA,210,19000,Founder,450,Dev Patel,⚡ Building SaaS in Fintech\n📍 Indiranagar\ndev...
27,TECHPARK_MEMES,350,16000,Comedy,250,Tech Park Memes,"😂 Jokes from Ecospace, Manyata & more\nbit.ly/..."
28,TECHWALK_BLR,430,11000,Media,320,Tech Walk Bangalore,🚶 Exploring tech parks & cafes\n📍 Ecoworld | M...
29,VENTURE_VIKRAM,120,30000,Investor,500,Vikram | Angel Investor,"💸 Helping founders go 0 to 1\nEx-Google, Ex-Am..."

In [8]:
df5 = df4.iloc[0:11].copy()
df5

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
0,_ANUJSINGHAL,1785,681000,Digital creator,248,Anuj Singhal,"Managing Editor, CNBC-Awaaz. Most trusted and ..."
1,AI_BANGALORE_NEWS,1340,38000,Media,200,AI Bangalore,🤖 Daily AI news from India\n📢 Startup & resear...
2,AI_BENGALURU,150,15200,Tech,140,AI Bengaluru,"🤖 AI trends, events & demos\n📍 BLR\nai-blr.tech"
3,BANGALORE_DATASCIENCE_CLUB,240,12700,Community,110,BLR Data Science Club,📊 ML sessions + Kaggle nights\n📍 MG Road WeWor...
4,BANGALORE_TECH_BRO,402,12500,Entrepreneur,890,Rahul | HSR Hustler,🚀 Building the next Unicorn in Fintech\n☕ 3rd ...
5,BLRCODERS_SPACE,340,25000,Community,300,BLR Coders Space,"👨‍💻 Coding news, memes\n📍 BLR\nblrcoders.space"
6,BLRDATASCIENCE_DAILY,540,15100,Media,150,Bangalore DS Daily,📊 Data + AI + ML\n👩‍🏫 Tutorials | Job alerts\n...
7,BLRONLINEJOBS,560,21000,Media,190,BLR Online Jobs,💼 Hiring in tech daily\n📍 BLR\nblronlinejobs.in
8,CODERS_OF_BANGALORE,300,17000,Community,280,Coders of Bangalore,👨‍💻 Showcasing BLR devs\n📍 BLR\ncodersofbangal...
9,DAILYDEV_BANGALORE,180,12200,Tech,200,Daily Dev Bangalore,📝 Tips | Tools | Tutorials\n📍 BLR\ndailydevblr.co
10,DEEPTECH_INDIA,900,24000,Media,290,DeepTech India,🛠️ Indian AI + Robotics + Chips\ndeeptechindia.ai

In [9]:
df5.rename(columns = {"username":"Username","no_of_posts":"Posts","no_of_followers":"Followers","type_of_page":"Type_Of_page","no_of_following":"Following","name":"Name","bio":"Bio"},inplace = True)
df5

,Username,Posts,Followers,Type_Of_page,Following,Name,Bio
0,_ANUJSINGHAL,1785,681000,Digital creator,248,Anuj Singhal,"Managing Editor, CNBC-Awaaz. Most trusted and ..."
1,AI_BANGALORE_NEWS,1340,38000,Media,200,AI Bangalore,🤖 Daily AI news from India\n📢 Startup & resear...
2,AI_BENGALURU,150,15200,Tech,140,AI Bengaluru,"🤖 AI trends, events & demos\n📍 BLR\nai-blr.tech"
3,BANGALORE_DATASCIENCE_CLUB,240,12700,Community,110,BLR Data Science Club,📊 ML sessions + Kaggle nights\n📍 MG Road WeWor...
4,BANGALORE_TECH_BRO,402,12500,Entrepreneur,890,Rahul | HSR Hustler,🚀 Building the next Unicorn in Fintech\n☕ 3rd ...
5,BLRCODERS_SPACE,340,25000,Community,300,BLR Coders Space,"👨‍💻 Coding news, memes\n📍 BLR\nblrcoders.space"
6,BLRDATASCIENCE_DAILY,540,15100,Media,150,Bangalore DS Daily,📊 Data + AI + ML\n👩‍🏫 Tutorials | Job alerts\n...
7,BLRONLINEJOBS,560,21000,Media,190,BLR Online Jobs,💼 Hiring in tech daily\n📍 BLR\nblronlinejobs.in
8,CODERS_OF_BANGALORE,300,17000,Community,280,Coders of Bangalore,👨‍💻 Showcasing BLR devs\n📍 BLR\ncodersofbangal...
9,DAILYDEV_BANGALORE,180,12200,Tech,200,Daily Dev Bangalore,📝 Tips | Tools | Tutorials\n📍 BLR\ndailydevblr.co
10,DEEPTECH_INDIA,900,24000,Media,290,DeepTech India,🛠️ Indian AI + Robotics + Chips\ndeeptechindia.ai

In [16]:
df5 = df5[["Name","Posts","Type_Of_page","Followers","Following","Bio","Username"]].copy()
df5

,Name,Posts,Type_Of_page,Followers,Following,Bio,Username
0,Anuj Singhal,1785,Digital creator,681000,248,"Managing Editor, CNBC-Awaaz. Most trusted and ...",_ANUJSINGHAL
1,AI Bangalore,1340,Media,38000,200,🤖 Daily AI news from India\n📢 Startup & resear...,AI_BANGALORE_NEWS
2,AI Bengaluru,150,Tech,15200,140,"🤖 AI trends, events & demos\n📍 BLR\nai-blr.tech",AI_BENGALURU
3,BLR Data Science Club,240,Community,12700,110,📊 ML sessions + Kaggle nights\n📍 MG Road WeWor...,BANGALORE_DATASCIENCE_CLUB
4,Rahul | HSR Hustler,402,Entrepreneur,12500,890,🚀 Building the next Unicorn in Fintech\n☕ 3rd ...,BANGALORE_TECH_BRO
5,BLR Coders Space,340,Community,25000,300,"👨‍💻 Coding news, memes\n📍 BLR\nblrcoders.space",BLRCODERS_SPACE
6,Bangalore DS Daily,540,Media,15100,150,📊 Data + AI + ML\n👩‍🏫 Tutorials | Job alerts\n...,BLRDATASCIENCE_DAILY
7,BLR Online Jobs,560,Media,21000,190,💼 Hiring in tech daily\n📍 BLR\nblronlinejobs.in,BLRONLINEJOBS
8,Coders of Bangalore,300,Community,17000,280,👨‍💻 Showcasing BLR devs\n📍 BLR\ncodersofbangal...,CODERS_OF_BANGALORE
9,Daily Dev Bangalore,180,Tech,12200,200,📝 Tips | Tools | Tutorials\n📍 BLR\ndailydevblr.co,DAILYDEV_BANGALORE
10,DeepTech India,900,Media,24000,290,🛠️ Indian AI + Robotics + Chips\ndeeptechindia.ai,DEEPTECH_INDIA

In [18]:
df5[["Name","Posts"]]

                     Name  Posts
0            Anuj Singhal   1785
1            AI Bangalore   1340
2            AI Bengaluru    150
3   BLR Data Science Club    240
4     Rahul | HSR Hustler    402
5        BLR Coders Space    340
6      Bangalore DS Daily    540
7         BLR Online Jobs    560
8     Coders of Bangalore    300
9     Daily Dev Bangalore    180
10         DeepTech India    900