In [1]:
import pandas as pd
df = pd.read_json("data.json")
df

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
0,techie_koramangala,420,9800,Software Engineer,310,Arjun M.,💻 Full-stack @ SaaS startup\n☕ Working from ca...
1,blrcoder_girl,150,6300,Tech Creator,120,Riya Codes,👩‍💻 Python | ML | Roadmaps\n🎥 Coding Reels + D...
2,hsr_startup_stories,980,22400,Media,95,Startup Stories HSR,🚀 Interviews with Bangalore founders\n🎙️ Weekl...
3,cloud_dev_blr,210,4500,Engineer,60,Naveen DevOps,☁️ AWS | Docker | K8s\n📍 Sarjapur\ngithub.com/...
4,koramangala_coffee_lover,300,7900,Cafe Explorer,180,Sana B.,☕ Reviewing Bangalore’s hidden coffee spots\n📍...
...,...,...,...,...,...,...,...
102,bangalore_backend,90,4800,Tech,60,BLR Backend Devs,🔧 Python | Go | Node\n📍 BLR\nbackendblr.tech
103,ecity_techies,140,3900,Community,55,E-city Techies,💼 Tech park life\n📍 Electronic City\necitytech...
104,fullstack_blr_club,110,7200,Community,85,Fullstack BLR Club,💻 MERN | Python | DevOps\n📍 JP Nagar\nfullstac...
105,coding_runners_blr,100,2500,Community,35,Coding Runners,🏃‍♂️ Running + coding\n📍 Cubbon Park\ncodingru...
106,bangalore_engineers_diary,270,8500,Blog,120,Engineers Diary BLR,📘 Life & tech rants\n📍 BLR\nmedium.com/@engine...

In [3]:
#First of all we perform first step of  data scientist EDA to analayse the data
#we have several methods of eda 
df.head()

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
0,techie_koramangala,420,9800,Software Engineer,310,Arjun M.,💻 Full-stack @ SaaS startup\n☕ Working from ca...
1,blrcoder_girl,150,6300,Tech Creator,120,Riya Codes,👩‍💻 Python | ML | Roadmaps\n🎥 Coding Reels + D...
2,hsr_startup_stories,980,22400,Media,95,Startup Stories HSR,🚀 Interviews with Bangalore founders\n🎙️ Weekl...
3,cloud_dev_blr,210,4500,Engineer,60,Naveen DevOps,☁️ AWS | Docker | K8s\n📍 Sarjapur\ngithub.com/...
4,koramangala_coffee_lover,300,7900,Cafe Explorer,180,Sana B.,☕ Reviewing Bangalore’s hidden coffee spots\n📍...

In [4]:
df.tail()

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
102,bangalore_backend,90,4800,Tech,60,BLR Backend Devs,🔧 Python | Go | Node\n📍 BLR\nbackendblr.tech
103,ecity_techies,140,3900,Community,55,E-city Techies,💼 Tech park life\n📍 Electronic City\necitytech...
104,fullstack_blr_club,110,7200,Community,85,Fullstack BLR Club,💻 MERN | Python | DevOps\n📍 JP Nagar\nfullstac...
105,coding_runners_blr,100,2500,Community,35,Coding Runners,🏃‍♂️ Running + coding\n📍 Cubbon Park\ncodingru...
106,bangalore_engineers_diary,270,8500,Blog,120,Engineers Diary BLR,📘 Life & tech rants\n📍 BLR\nmedium.com/@engine...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   username         107 non-null    object
 1   no_of_posts      107 non-null    int64
 2   no_of_followers  107 non-null    int64
 3   type_of_page     107 non-null    object
 4   no_of_following  107 non-null    int64
 5   name             107 non-null    object
 6   bio              107 non-null    object
dtypes: int64(3), object(4)
memory usage: 6.0+ KB

In [6]:
df.describe()

       no_of_posts  no_of_followers  no_of_following
count   107.000000       107.000000       107.000000
mean    310.560748     15274.925234       138.934579
std     384.174297     65480.455307       133.551578
min      42.000000       216.000000        10.000000
25%     100.000000      3400.000000        42.000000
50%     180.000000      6800.000000        95.000000
75%     330.000000     12100.000000       200.000000
max    2300.000000    681000.000000       890.000000

In [7]:
df.shape

(107, 7)

In [8]:
df.size

749

In [10]:
df.ndim

2

In [11]:
df.dtypes

username           object
no_of_posts         int64
no_of_followers     int64
type_of_page       object
no_of_following     int64
name               object
bio                object
dtype: object

In [12]:
df

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
0,techie_koramangala,420,9800,Software Engineer,310,Arjun M.,💻 Full-stack @ SaaS startup\n☕ Working from ca...
1,blrcoder_girl,150,6300,Tech Creator,120,Riya Codes,👩‍💻 Python | ML | Roadmaps\n🎥 Coding Reels + D...
2,hsr_startup_stories,980,22400,Media,95,Startup Stories HSR,🚀 Interviews with Bangalore founders\n🎙️ Weekl...
3,cloud_dev_blr,210,4500,Engineer,60,Naveen DevOps,☁️ AWS | Docker | K8s\n📍 Sarjapur\ngithub.com/...
4,koramangala_coffee_lover,300,7900,Cafe Explorer,180,Sana B.,☕ Reviewing Bangalore’s hidden coffee spots\n📍...
...,...,...,...,...,...,...,...
102,bangalore_backend,90,4800,Tech,60,BLR Backend Devs,🔧 Python | Go | Node\n📍 BLR\nbackendblr.tech
103,ecity_techies,140,3900,Community,55,E-city Techies,💼 Tech park life\n📍 Electronic City\necitytech...
104,fullstack_blr_club,110,7200,Community,85,Fullstack BLR Club,💻 MERN | Python | DevOps\n📍 JP Nagar\nfullstac...
105,coding_runners_blr,100,2500,Community,35,Coding Runners,🏃‍♂️ Running + coding\n📍 Cubbon Park\ncodingru...
106,bangalore_engineers_diary,270,8500,Blog,120,Engineers Diary BLR,📘 Life & tech rants\n📍 BLR\nmedium.com/@engine...

In [13]:
df[["name","bio"]]

                    name                                                bio
0               Arjun M.  💻 Full-stack @ SaaS startup\n☕ Working from ca...
1             Riya Codes  👩‍💻 Python | ML | Roadmaps\n🎥 Coding Reels + D...
2    Startup Stories HSR  🚀 Interviews with Bangalore founders\n🎙️ Weekl...
3          Naveen DevOps  ☁️ AWS | Docker | K8s\n📍 Sarjapur\ngithub.com/...
4                Sana B.  ☕ Reviewing Bangalore’s hidden coffee spots\n📍...
..                   ...                                                ...
102     BLR Backend Devs       🔧 Python | Go | Node\n📍 BLR\nbackendblr.tech
103       E-city Techies  💼 Tech park life\n📍 Electronic City\necitytech...
104   Fullstack BLR Club  💻 MERN | Python | DevOps\n📍 JP Nagar\nfullstac...
105       Coding Runners  🏃‍♂️ Running + coding\n📍 Cubbon Park\ncodingru...
106  Engineers Diary BLR  📘 Life & tech rants\n📍 BLR\nmedium.com/@engine...

[107 rows x 2 columns]

In [17]:
df.loc[0,"name"]

'Arjun M.'

In [21]:
df.iloc[0,5]

'Arjun M.'

In [29]:
df.query("no_of_following>800 ")

,username,no_of_posts,no_of_followers,type_of_page,no_of_following,name,bio
49,bangalore_tech_bro,402,12500,Entrepreneur,890,Rahul | HSR Hustler,🚀 Building the next Unicorn in Fintech\n☕ 3rd ...