In [1]:
pip install kaggle

Requirement already satisfied: kaggle in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (2.0.1)
Requirement already satisfied: bleach in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.17 in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from kaggle) (0.1.19)
Requirement already satisfied: packaging in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from kaggle) (7.34.1)
Requirement already satisfied: python-dateutil in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from kaggle) (2.6.3)
Requirement already satisfied: webencodings in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/myenv/lib/python3.14/site-packages (from requests->kaggle) (2026.1.4)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from kaggle.api.kaggle_api_extended import KaggleApi

api = KaggleApi()
api.authenticate()

print("✅ Authenticated!")

✅ Authenticated!

In [3]:
api.dataset_download_files('amruthayenikonda/dirty-dataset-to-practice-data-cleaning', path='./data', unzip=True)

print("✅ Dataset downloaded!")

Dataset URL: https://www.kaggle.com/datasets/amruthayenikonda/dirty-dataset-to-practice-data-cleaning
✅ Dataset downloaded!

In [4]:
import os
files = os.listdir('./data')
print("Files downloaded:")
for file in files:
    print(f"  - {file}")

Files downloaded:
  - my_file (1).csv

In [5]:
import pandas as pd

df = pd.read_csv('./data/my_file (1).csv')
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [6]:
df1=df[["Artist","Shows","Tour title","Year(s)","Average gross","Peak","Rank"]].copy()
df1

,Artist,Shows,Tour title,Year(s),Average gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,"$13,928,571",1,1
1,Beyoncé,56,Renaissance World Tour,2023,"$10,353,571",1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,"$4,835,294",1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,"$2,546,795",2[7],4
4,Taylor Swift,53,Reputation Stadium Tour,2018,"$6,522,173",2[4],5
5,Madonna,88,The MDNA Tour,2012,"$3,467,709",2[4],6
6,Celine Dion,131,Taking Chances World Tour,2008–2009,"$2,137,405",2[10],7
7,Pink,41,Summer Carnival †,2023–2024,"$6,282,927",NaN,7
8,Beyoncé,49,The Formation World Tour,2016,"$5,226,215",NaN,9
9,Taylor Swift,85,The 1989 World Tour,2015,"$2,945,882",NaN,10
10,Beyoncé,132,The Mrs. Carter Show World Tour,2013–2014,"$1,735,606",NaN,11
11,Lady Gaga,203,The Monster Ball Tour *,2009–2011,"$1,118,227",NaN,12
12,Katy Perry,151,Prismatic World Tour,2014–2015,"$1,350,993",NaN,13
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,"$615,385",1[20],14
14,Madonna,60,Confessions Tour,2006,"$3,233,333",2[c],15
15,Pink,142,The Truth About Love Tour,2013–2014,"$1,295,775",NaN,16
16,Lady Gaga,98,Born This Way Ball,2012–2013,"$1,734,694",NaN,17
17,Madonna,82,Rebel Heart Tour,2015–2016,"$2,070,732",NaN,18
18,Adele,121,Adele Live 2016,2016–2017,"$1,385,950",NaN,19
19,Taylor Swift,86,The Red Tour,2013–2014,"$1,744,186",NaN,20

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Artist         20 non-null     str
 1   Shows          20 non-null     int64
 2   Tour title     20 non-null     str
 3   Year(s)        20 non-null     str
 4   Average gross  20 non-null     str
 5   Peak           9 non-null      str
 6   Rank           20 non-null     int64
dtypes: int64(2), str(5)
memory usage: 1.2 KB

In [8]:
df.at[0,"Artist"]

'Taylor Swift'

In [9]:
df2 =df1.dropna().copy()
df2

,Artist,Shows,Tour title,Year(s),Average gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,"$13,928,571",1,1
1,Beyoncé,56,Renaissance World Tour,2023,"$10,353,571",1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,"$4,835,294",1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,"$2,546,795",2[7],4
4,Taylor Swift,53,Reputation Stadium Tour,2018,"$6,522,173",2[4],5
5,Madonna,88,The MDNA Tour,2012,"$3,467,709",2[4],6
6,Celine Dion,131,Taking Chances World Tour,2008–2009,"$2,137,405",2[10],7
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,"$615,385",1[20],14
14,Madonna,60,Confessions Tour,2006,"$3,233,333",2[c],15

In [10]:
df2

,Artist,Shows,Tour title,Year(s),Average gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,"$13,928,571",1,1
1,Beyoncé,56,Renaissance World Tour,2023,"$10,353,571",1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,"$4,835,294",1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,"$2,546,795",2[7],4
4,Taylor Swift,53,Reputation Stadium Tour,2018,"$6,522,173",2[4],5
5,Madonna,88,The MDNA Tour,2012,"$3,467,709",2[4],6
6,Celine Dion,131,Taking Chances World Tour,2008–2009,"$2,137,405",2[10],7
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,"$615,385",1[20],14
14,Madonna,60,Confessions Tour,2006,"$3,233,333",2[c],15

In [11]:
df2.drop_duplicates()

,Artist,Shows,Tour title,Year(s),Average gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,"$13,928,571",1,1
1,Beyoncé,56,Renaissance World Tour,2023,"$10,353,571",1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,"$4,835,294",1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,"$2,546,795",2[7],4
4,Taylor Swift,53,Reputation Stadium Tour,2018,"$6,522,173",2[4],5
5,Madonna,88,The MDNA Tour,2012,"$3,467,709",2[4],6
6,Celine Dion,131,Taking Chances World Tour,2008–2009,"$2,137,405",2[10],7
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,"$615,385",1[20],14
14,Madonna,60,Confessions Tour,2006,"$3,233,333",2[c],15

In [12]:
df3=df2.iloc[0:4,0:7].copy()
df3

,Artist,Shows,Tour title,Year(s),Average gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,"$13,928,571",1,1
1,Beyoncé,56,Renaissance World Tour,2023,"$10,353,571",1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,"$4,835,294",1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,"$2,546,795",2[7],4

In [13]:
df4=df2.iloc[6:15,0:7].copy()
df4

,Artist,Shows,Tour title,Year(s),Average gross,Peak,Rank
6,Celine Dion,131,Taking Chances World Tour,2008–2009,"$2,137,405",2[10],7
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,"$615,385",1[20],14
14,Madonna,60,Confessions Tour,2006,"$3,233,333",2[c],15

In [14]:
df5=pd.concat([df3,df4])
df5

,Artist,Shows,Tour title,Year(s),Average gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,"$13,928,571",1,1
1,Beyoncé,56,Renaissance World Tour,2023,"$10,353,571",1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,"$4,835,294",1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,"$2,546,795",2[7],4
6,Celine Dion,131,Taking Chances World Tour,2008–2009,"$2,137,405",2[10],7
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,"$615,385",1[20],14
14,Madonna,60,Confessions Tour,2006,"$3,233,333",2[c],15

In [15]:
df6=df5.rename(columns={"Tour title":"Tour_title","Year(s)":"Years","Average gross":"Average_gross"}).copy()
df6

,Artist,Shows,Tour_title,Years,Average_gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,"$13,928,571",1,1
1,Beyoncé,56,Renaissance World Tour,2023,"$10,353,571",1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,"$4,835,294",1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,"$2,546,795",2[7],4
6,Celine Dion,131,Taking Chances World Tour,2008–2009,"$2,137,405",2[10],7
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,"$615,385",1[20],14
14,Madonna,60,Confessions Tour,2006,"$3,233,333",2[c],15

In [16]:
df7=df6.sort_values(["Rank"],ascending=True).copy()
df7

,Artist,Shows,Tour_title,Years,Average_gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,"$13,928,571",1,1
1,Beyoncé,56,Renaissance World Tour,2023,"$10,353,571",1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,"$4,835,294",1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,"$2,546,795",2[7],4
6,Celine Dion,131,Taking Chances World Tour,2008–2009,"$2,137,405",2[10],7
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,"$615,385",1[20],14
14,Madonna,60,Confessions Tour,2006,"$3,233,333",2[c],15

In [17]:
df7.reset_index(drop=True)

,Artist,Shows,Tour_title,Years,Average_gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,"$13,928,571",1,1
1,Beyoncé,56,Renaissance World Tour,2023,"$10,353,571",1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,"$4,835,294",1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,"$2,546,795",2[7],4
4,Celine Dion,131,Taking Chances World Tour,2008–2009,"$2,137,405",2[10],7
5,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,"$615,385",1[20],14
6,Madonna,60,Confessions Tour,2006,"$3,233,333",2[c],15

In [18]:

df7['Average_gross'] = df7['Average_gross'].str.replace('$', '').str.replace(',', '').copy()
df7

,Artist,Shows,Tour_title,Years,Average_gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,13928571,1,1
1,Beyoncé,56,Renaissance World Tour,2023,10353571,1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,4835294,1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,2546795,2[7],4
6,Celine Dion,131,Taking Chances World Tour,2008–2009,2137405,2[10],7
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,615385,1[20],14
14,Madonna,60,Confessions Tour,2006,3233333,2[c],15

In [21]:
df7

,Artist,Shows,Tour_title,Years,Average_gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,13928571,1,1
1,Beyoncé,56,Renaissance World Tour,2023,10353571,1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,4835294,1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,2546795,2[7],4
6,Celine Dion,131,Taking Chances World Tour,2008–2009,2137405,2[10],7
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,615385,1[20],14
14,Madonna,60,Confessions Tour,2006,3233333,2[c],15

In [24]:
df7.iloc[0:6,0:6].copy()

,Artist,Shows,Tour_title,Years,Average_gross,Peak
0,Taylor Swift,56,The Eras Tour †,2023–2024,13928571,1
1,Beyoncé,56,Renaissance World Tour,2023,10353571,1
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,4835294,1[4]
3,Pink,156,Beautiful Trauma World Tour,2018–2019,2546795,2[7]
6,Celine Dion,131,Taking Chances World Tour,2008–2009,2137405,2[10]
13,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,615385,1[20]

In [32]:
df7.reset_index(drop=True,inplace=True)
df7

,Artist,Shows,Tour_title,Years,Average_gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,13928571,1,1
1,Beyoncé,56,Renaissance World Tour,2023,10353571,1,2
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,4835294,1[4],3
3,Pink,156,Beautiful Trauma World Tour,2018–2019,2546795,2[7],4
4,Celine Dion,131,Taking Chances World Tour,2008–2009,2137405,2[10],7
5,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,615385,1[20],14
6,Madonna,60,Confessions Tour,2006,3233333,2[c],15

In [39]:
df7["Rank"] = df7["Artist"].rank() 
df7

,Artist,Shows,Tour_title,Years,Average_gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,13928571,1,7.0
1,Beyoncé,56,Renaissance World Tour,2023,10353571,1,1.0
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,4835294,1[4],4.5
3,Pink,156,Beautiful Trauma World Tour,2018–2019,2546795,2[7],6.0
4,Celine Dion,131,Taking Chances World Tour,2008–2009,2137405,2[10],2.0
5,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,615385,1[20],3.0
6,Madonna,60,Confessions Tour,2006,3233333,2[c],4.5

In [50]:
df7["Rank"] = df7["Rank"].astype(int)
df7

,Artist,Shows,Tour_title,Years,Average_gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,13928571,1,7
1,Beyoncé,56,Renaissance World Tour,2023,10353571,1,1
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,4835294,1[4],4
3,Pink,156,Beautiful Trauma World Tour,2018–2019,2546795,2[7],6
4,Celine Dion,131,Taking Chances World Tour,2008–2009,2137405,2[10],2
5,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,615385,1[20],3
6,Madonna,60,Confessions Tour,2006,3233333,2[c],4

In [55]:
df7.to_csv("Singer.csv",index=False)

In [60]:
df7["Average_gross"]=df7["Average_gross"].astype(int)
df7

,Artist,Shows,Tour_title,Years,Average_gross,Peak,Rank
0,Taylor Swift,56,The Eras Tour †,2023–2024,13928571,1,7
1,Beyoncé,56,Renaissance World Tour,2023,10353571,1,1
2,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,4835294,1[4],4
3,Pink,156,Beautiful Trauma World Tour,2018–2019,2546795,2[7],6
4,Celine Dion,131,Taking Chances World Tour,2008–2009,2137405,2[10],2
5,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,615385,1[20],3
6,Madonna,60,Confessions Tour,2006,3233333,2[c],4

In [70]:
df8=df7.groupby('Artist')['Average_gross'].agg(average_mean="mean").copy()
df8

              average_mean
Artist
Beyoncé         10353571.0
Celine Dion      2137405.0
Cher              615385.0
Madonna          4034313.5
Pink             2546795.0
Taylor Swift    13928571.0

In [89]:
df9 =pd.merge(df7,df8,on="Artist",how="outer").copy()
df9

,Artist,Shows,Tour_title,Years,Average_gross,Peak,Rank,average_mean
0,Beyoncé,56,Renaissance World Tour,2023,10353571,1,1,10353571.0
1,Celine Dion,131,Taking Chances World Tour,2008–2009,2137405,2[10],2,2137405.0
2,Cher,325,Living Proof: The Farewell Tour ‡[21][a],2002–2005,615385,1[20],3,615385.0
3,Madonna,85,Sticky & Sweet Tour ‡[4][a],2008–2009,4835294,1[4],4,4034313.5
4,Madonna,60,Confessions Tour,2006,3233333,2[c],4,4034313.5
5,Pink,156,Beautiful Trauma World Tour,2018–2019,2546795,2[7],6,2546795.0
6,Taylor Swift,56,The Eras Tour †,2023–2024,13928571,1,7,13928571.0

In [92]:
df9=df9[["Rank","Artist","Shows","Years","Average_gross","Tour_title","average_mean"]]
df9

,Rank,Artist,Shows,Years,Average_gross,Tour_title,average_mean
0,1,Beyoncé,56,2023,10353571,Renaissance World Tour,10353571.0
1,2,Celine Dion,131,2008–2009,2137405,Taking Chances World Tour,2137405.0
2,3,Cher,325,2002–2005,615385,Living Proof: The Farewell Tour ‡[21][a],615385.0
3,4,Madonna,85,2008–2009,4835294,Sticky & Sweet Tour ‡[4][a],4034313.5
4,4,Madonna,60,2006,3233333,Confessions Tour,4034313.5
5,6,Pink,156,2018–2019,2546795,Beautiful Trauma World Tour,2546795.0
6,7,Taylor Swift,56,2023–2024,13928571,The Eras Tour †,13928571.0

In [98]:
df10 =df9.rename(columns={"average_mean":"Average_mean"}).copy()
df10

,Rank,Artist,Shows,Years,Average_gross,Tour_title,Average_mean
0,1,Beyoncé,56,2023,10353571,Renaissance World Tour,10353571.0
1,2,Celine Dion,131,2008–2009,2137405,Taking Chances World Tour,2137405.0
2,3,Cher,325,2002–2005,615385,Living Proof: The Farewell Tour ‡[21][a],615385.0
3,4,Madonna,85,2008–2009,4835294,Sticky & Sweet Tour ‡[4][a],4034313.5
4,4,Madonna,60,2006,3233333,Confessions Tour,4034313.5
5,6,Pink,156,2018–2019,2546795,Beautiful Trauma World Tour,2546795.0
6,7,Taylor Swift,56,2023–2024,13928571,The Eras Tour †,13928571.0

In [99]:
df10

,Rank,Artist,Shows,Years,Average_gross,Tour_title,Average_mean
0,1,Beyoncé,56,2023,10353571,Renaissance World Tour,10353571.0
1,2,Celine Dion,131,2008–2009,2137405,Taking Chances World Tour,2137405.0
2,3,Cher,325,2002–2005,615385,Living Proof: The Farewell Tour ‡[21][a],615385.0
3,4,Madonna,85,2008–2009,4835294,Sticky & Sweet Tour ‡[4][a],4034313.5
4,4,Madonna,60,2006,3233333,Confessions Tour,4034313.5
5,6,Pink,156,2018–2019,2546795,Beautiful Trauma World Tour,2546795.0
6,7,Taylor Swift,56,2023–2024,13928571,The Eras Tour †,13928571.0

In [106]:
df11 = df10.sort_values("Years",ascending=False).copy()
df11

,Rank,Artist,Shows,Years,Average_gross,Tour_title,Average_mean
6,7,Taylor Swift,56,2023–2024,13928571,The Eras Tour †,13928571.0
0,1,Beyoncé,56,2023,10353571,Renaissance World Tour,10353571.0
5,6,Pink,156,2018–2019,2546795,Beautiful Trauma World Tour,2546795.0
1,2,Celine Dion,131,2008–2009,2137405,Taking Chances World Tour,2137405.0
3,4,Madonna,85,2008–2009,4835294,Sticky & Sweet Tour ‡[4][a],4034313.5
4,4,Madonna,60,2006,3233333,Confessions Tour,4034313.5
2,3,Cher,325,2002–2005,615385,Living Proof: The Farewell Tour ‡[21][a],615385.0

In [107]:
df11.reset_index(drop=True,inplace=True)
df11

,Rank,Artist,Shows,Years,Average_gross,Tour_title,Average_mean
0,7,Taylor Swift,56,2023–2024,13928571,The Eras Tour †,13928571.0
1,1,Beyoncé,56,2023,10353571,Renaissance World Tour,10353571.0
2,6,Pink,156,2018–2019,2546795,Beautiful Trauma World Tour,2546795.0
3,2,Celine Dion,131,2008–2009,2137405,Taking Chances World Tour,2137405.0
4,4,Madonna,85,2008–2009,4835294,Sticky & Sweet Tour ‡[4][a],4034313.5
5,4,Madonna,60,2006,3233333,Confessions Tour,4034313.5
6,3,Cher,325,2002–2005,615385,Living Proof: The Farewell Tour ‡[21][a],615385.0

In [115]:
df12=df11.groupby('Artist').agg({
    'Shows': 'sum',
    'Average_gross': ['mean'],
    'Rank': ['max','min']
})
df12

             Shows Average_gross Rank
               sum          mean  max min
Artist
Beyoncé         56    10353571.0    1   1
Celine Dion    131     2137405.0    2   2
Cher           325      615385.0    3   3
Madonna        145     4034313.5    4   4
Pink           156     2546795.0    6   6
Taylor Swift    56    13928571.0    7   7

In [117]:
df13=pd.merge(df12,df11,on="Artist",how="outer")
df13

MergeError: Not allowed to merge between different levels. (2 levels on the left, 1 on the right)