In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
import pandas as pd 
data = pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [85]:
data = {
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115, 116, 117, 118, 119, 120],

    "name": ["Amit", "Riya", "Karan", "Sneha", "Rahul", "Pooja", "Vikas", "Neha", "Arjun", "Meera",
             "Rohit", "Simran", "Aditya", "Kavya", "Manish", "Anjali", "Suresh", "Priya", "Deepak", "Nikita"],

    "age": [25, 28, 30, 27, 35, 29, 31, 26, 32, 24,
            33, 28, 27, 26, 34, 29, 36, 31, 30, 28],

    "department": ["IT", "HR", "Finance", "IT", "Sales", "HR", "Finance", "IT", "Sales", "HR",
                   "Finance", "IT", "HR", "Sales", "IT", "Finance", "HR", "Sales", "IT", "Finance"],

    "salary": [50000, 45000, 60000, 52000, 70000, 48000, 62000, 51000, 72000, 46000,
               65000, 53000, 49000, 71000, 68000, 64000, 47000, 73000, 69000, 66000],

    "experience_years": [2, 4, 6, 3, 10, 5, 7, 2, 8, 1,
                         9, 3, 4, 7, 11, 6, 12, 8, 10, 9],

    "city": ["Delhi", "Mumbai", "Bangalore", "Delhi", "Pune", "Mumbai", "Chennai", "Delhi", "Pune", "Mumbai",
             "Bangalore", "Delhi", "Mumbai", "Pune", "Chennai", "Bangalore", "Delhi", "Pune", "Mumbai", "Chennai"]
}

df = pd.DataFrame(data)
df
df1=df.rename(columns={"employee_id": "Employee_id","name":"Name","age":"Age","department":"Department","salary":"Salary","experience_years":"Experience_years","city":"City"}).copy()

In [95]:
df1=df1[["Name","Age","Department","Salary","City","Experience_years","Employee_id"]]
df1

      Name  Age Department  Salary       City  Experience_years  Employee_id
0     Amit   25         IT   50000      Delhi                 2          101
1     Riya   28         HR   45000     Mumbai                 4          102
2    Karan   30    Finance   60000  Bangalore                 6          103
3    Sneha   27         IT   52000      Delhi                 3          104
4    Rahul   35      Sales   70000       Pune                10          105
5    Pooja   29         HR   48000     Mumbai                 5          106
6    Vikas   31    Finance   62000    Chennai                 7          107
7     Neha   26         IT   51000      Delhi                 2          108
8    Arjun   32      Sales   72000       Pune                 8          109
9    Meera   24         HR   46000     Mumbai                 1          110
10   Rohit   33    Finance   65000  Bangalore                 9          111
11  Simran   28         IT   53000      Delhi                 3          112
12  Aditya   27         HR   49000     Mumbai                 4          113
13   Kavya   26      Sales   71000       Pune                 7          114
14  Manish   34         IT   68000    Chennai                11          115
15  Anjali   29    Finance   64000  Bangalore                 6          116
16  Suresh   36         HR   47000      Delhi                12          117
17   Priya   31      Sales   73000       Pune                 8          118
18  Deepak   30         IT   69000     Mumbai                10          119
19  Nikita   28    Finance   66000    Chennai                 9          120

In [110]:
df2=df1.sort_values(["Name","Age"],ascending=True).copy()
df2
df2.reset_index(drop=True,inplace=True)
df2
df2.sort_index()
df2

      Name  Age Department  Salary       City  Experience_years  Employee_id
0   Aditya   27         HR   49000     Mumbai                 4          113
1     Amit   25         IT   50000      Delhi                 2          101
2   Anjali   29    Finance   64000  Bangalore                 6          116
3    Arjun   32      Sales   72000       Pune                 8          109
4   Deepak   30         IT   69000     Mumbai                10          119
5    Karan   30    Finance   60000  Bangalore                 6          103
6    Kavya   26      Sales   71000       Pune                 7          114
7   Manish   34         IT   68000    Chennai                11          115
8    Meera   24         HR   46000     Mumbai                 1          110
9     Neha   26         IT   51000      Delhi                 2          108
10  Nikita   28    Finance   66000    Chennai                 9          120
11   Pooja   29         HR   48000     Mumbai                 5          106
12   Priya   31      Sales   73000       Pune                 8          118
13   Rahul   35      Sales   70000       Pune                10          105
14    Riya   28         HR   45000     Mumbai                 4          102
15   Rohit   33    Finance   65000  Bangalore                 9          111
16  Simran   28         IT   53000      Delhi                 3          112
17   Sneha   27         IT   52000      Delhi                 3          104
18  Suresh   36         HR   47000      Delhi                12          117
19   Vikas   31    Finance   62000    Chennai                 7          107

In [115]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df.tail

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]