In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
import pandas as pd 
data = pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [51]:
data = {
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115, 116, 117, 118, 119, 120],

    "name": ["Amit", "Riya", "Karan", "Sneha", "Rahul", "Pooja", "Vikas", "Neha", "Arjun", "Meera",
             "Rohit", "Simran", "Aditya", "Kavya", "Manish", "Anjali", "Suresh", "Priya", "Deepak", "Nikita"],

    "age": [25, 28, 30, 27, 35, 29, 31, 26, 32, 24,
            33, 28, 27, 26, 34, 29, 36, 31, 30, 28],

    "department": ["IT", "HR", "Finance", "IT", "Sales", "HR", "Finance", "IT", "Sales", "HR",
                   "Finance", "IT", "HR", "Sales", "IT", "Finance", "HR", "Sales", "IT", "Finance"],

    "salary": [50000, 45000, 60000, 52000, 70000, 48000, 62000, 51000, 72000, 46000,
               65000, 53000, 49000, 71000, 68000, 64000, 47000, 73000, 69000, 66000],

    "experience_years": [2, 4, 6, 3, 10, 5, 7, 2, 8, 1,
                         9, 3, 4, 7, 11, 6, 12, 8, 10, 9],

    "city": ["Delhi", "Mumbai", "Bangalore", "Delhi", "Pune", "Mumbai", "Chennai", "Delhi", "Pune", "Mumbai",
             "Bangalore", "Delhi", "Mumbai", "Pune", "Chennai", "Bangalore", "Delhi", "Pune", "Mumbai", "Chennai"]
}

df = pd.DataFrame(data)
df
df1=df.rename(columns={"employee_id": "Employee_id","name":"Name","age":"Age","department":"Department","salary":"Salary","experience_years":"Experience_years","city":"City"}).copy()

In [54]:
df1=df1[["Name","Age","Department","Salary","City","Experience_years","Employee_id"]]
df1

      Name  Age Department  Salary       City  Experience_years  Employee_id
0     Amit   25         IT   50000      Delhi                 2          101
1     Riya   28         HR   45000     Mumbai                 4          102
2    Karan   30    Finance   60000  Bangalore                 6          103
3    Sneha   27         IT   52000      Delhi                 3          104
4    Rahul   35      Sales   70000       Pune                10          105
5    Pooja   29         HR   48000     Mumbai                 5          106
6    Vikas   31    Finance   62000    Chennai                 7          107
7     Neha   26         IT   51000      Delhi                 2          108
8    Arjun   32      Sales   72000       Pune                 8          109
9    Meera   24         HR   46000     Mumbai                 1          110
10   Rohit   33    Finance   65000  Bangalore                 9          111
11  Simran   28         IT   53000      Delhi                 3          112
12  Aditya   27         HR   49000     Mumbai                 4          113
13   Kavya   26      Sales   71000       Pune                 7          114
14  Manish   34         IT   68000    Chennai                11          115
15  Anjali   29    Finance   64000  Bangalore                 6          116
16  Suresh   36         HR   47000      Delhi                12          117
17   Priya   31      Sales   73000       Pune                 8          118
18  Deepak   30         IT   69000     Mumbai                10          119
19  Nikita   28    Finance   66000    Chennai                 9          120

In [55]:
df

    employee_id    name  age department  salary  experience_years       city
0           101    Amit   25         IT   50000                 2      Delhi
1           102    Riya   28         HR   45000                 4     Mumbai
2           103   Karan   30    Finance   60000                 6  Bangalore
3           104   Sneha   27         IT   52000                 3      Delhi
4           105   Rahul   35      Sales   70000                10       Pune
5           106   Pooja   29         HR   48000                 5     Mumbai
6           107   Vikas   31    Finance   62000                 7    Chennai
7           108    Neha   26         IT   51000                 2      Delhi
8           109   Arjun   32      Sales   72000                 8       Pune
9           110   Meera   24         HR   46000                 1     Mumbai
10          111   Rohit   33    Finance   65000                 9  Bangalore
11          112  Simran   28         IT   53000                 3      Delhi
12          113  Aditya   27         HR   49000                 4     Mumbai
13          114   Kavya   26      Sales   71000                 7       Pune
14          115  Manish   34         IT   68000                11    Chennai
15          116  Anjali   29    Finance   64000                 6  Bangalore
16          117  Suresh   36         HR   47000                12      Delhi
17          118   Priya   31      Sales   73000                 8       Pune
18          119  Deepak   30         IT   69000                10     Mumbai
19          120  Nikita   28    Finance   66000                 9    Chennai

In [60]:
df1.to_csv("Employee_data")
df1

      Name  Age Department  Salary       City  Experience_years  Employee_id
0     Amit   25         IT   50000      Delhi                 2          101
1     Riya   28         HR   45000     Mumbai                 4          102
2    Karan   30    Finance   60000  Bangalore                 6          103
3    Sneha   27         IT   52000      Delhi                 3          104
4    Rahul   35      Sales   70000       Pune                10          105
5    Pooja   29         HR   48000     Mumbai                 5          106
6    Vikas   31    Finance   62000    Chennai                 7          107
7     Neha   26         IT   51000      Delhi                 2          108
8    Arjun   32      Sales   72000       Pune                 8          109
9    Meera   24         HR   46000     Mumbai                 1          110
10   Rohit   33    Finance   65000  Bangalore                 9          111
11  Simran   28         IT   53000      Delhi                 3          112
12  Aditya   27         HR   49000     Mumbai                 4          113
13   Kavya   26      Sales   71000       Pune                 7          114
14  Manish   34         IT   68000    Chennai                11          115
15  Anjali   29    Finance   64000  Bangalore                 6          116
16  Suresh   36         HR   47000      Delhi                12          117
17   Priya   31      Sales   73000       Pune                 8          118
18  Deepak   30         IT   69000     Mumbai                10          119
19  Nikita   28    Finance   66000    Chennai                 9          120